id,router,input,route_time,expert,result_or_error
0,simple,query_0,0.000001,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
1,simple,query_1,0.000001,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
2,simple,query_2,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
3,simple,query_3,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
4,simple,query_4,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
5,simple,query_5,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
6,simple,query_6,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
7,simple,query_7,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
8,simple,query_8,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
9,simple,query_9,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
10,simple,query_10,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
11,simple,query_11,0.000000,Payments,ERROR: TypeError: amain.<locals>.generate_callable() got an unexpected keyword argument 'max_new_tokens'
